# Generated by Django 3.2.8 on 2021-10-29 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=256, verbose_name='Название должности')),
            ],
        ),
        migrations.RenameField(
            model_name='subdivision',
            old_name='name',
            new_name='subdivision_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Должность'),
        ),
    ]
